name: Workflows
on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
  workflow_dispatch:
  
jobs:
  shell-execution-for-trigger:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Display the output of echo
        run: echo "Workflow run happened!"

  lint-code-linter:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true 
          DEFAULT_BRANCH: master
          DISABLE_ERRORS: true 
          VALIDATE_JAVA: true 
          
  build-code-maven:
    runs-on: ubuntu-latest
    needs:  lint-code-linter
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }} 
          cache: maven

      - name: Build with Maven
        run: |
          mvn verify sonar:sonar \
          -Dsonar.projectKey=cagrirepo_basic-http-server \
          -Dsonar.organization=cagrirepo \
          -Dsonar.host.url=https://sonarcloud.io
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  snyk-security-scan:
    runs-on: ubuntu-latest
    needs: build-code-maven
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBB_TOKEN }}
        with:
          sarif_file: snyk.sarif
          
  on-demand-trigger:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Manual Trigger
        run: echo "This is a manual trigger happened!"
