name: run shell command
on: [push, pull_request]
jobs:
    shell-execution:
        runs-on: ubuntu-latest
        steps:
          - name: Display the output of echo
            run: echo "Workflow run happened!"
